/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

/**
 *
 * @author rortiz
 */
public class JFpagFinal extends javax.swing.JFrame {

    static Datos datoPagFinal;
    static boolean pregunta1;
    static String nombreU;
    boolean ganop1;
    //=========PREGUNTA 1 20%============
    //for(int i=5;i>=1;i--){ System.out.println(i);} (ChkPreg1)
    public boolean Pregunta1_1=false;
    //for(int i=5;i>0;i--){ System.out.println(i);}  (ChkPreg2)  
    public boolean Pregunta1_2=false;
    //mala
    public boolean Pregunta1_3=false;
    //mala
    public boolean Pregunta1_4=false;

    public boolean isPregunta1_1() {
        return Pregunta1_1;
    }
//==============PREGUNTA 2 20%=========
    //Ninguna de las anteriores (Rbt4)
    public boolean Pregunta2=false;
  
 //================== CONSTRUCTOR ====================================   
    public JFpagFinal(String usuario,Datos dato) {
        initComponents();
        nombreU = usuario;
        LblNombre.setText("Hola "+nombreU+ ", este es su resultado."); 
        datoPagFinal = dato;
    }

    //=========================GET AND SET====================================

    public boolean isPregunta2() {
        return Pregunta2;
    }

    public void setPregunta2(boolean Pregunta2) {
        this.Pregunta2 = Pregunta2;
    }
    
    public void setPregunta1_1(boolean Pregunta1_1) {
        this.Pregunta1_1 = Pregunta1_1;
    }

    public boolean isPregunta1_2() {
        
        return Pregunta1_2;
        
    }

    public void setPregunta1_2(boolean Pregunta1_2) {
        this.Pregunta1_2 = Pregunta1_2;
    }

    public boolean isPregunta1_3() {
        return Pregunta1_3;
    }

    public void setPregunta1_3(boolean Pregunta1_3) {
        this.Pregunta1_3 = Pregunta1_3;
    }

    public boolean isPregunta1_4() {
        return Pregunta1_4;
    }

    public void setPregunta1_4(boolean Pregunta1_4) {
        this.Pregunta1_4 = Pregunta1_4;
    }
    
//====================== METODOS ====================================    
    
    private void establecerPreguntaUno(){
              
        if(isPregunta1_1() && isPregunta1_2()){
            ganop1=true;
        }else{
             ganop1=false;
        }
        if(isPregunta1_1()){
            ChkOpt1P1.isSelected();
        }
        if(isPregunta1_2()){
            ChkOpt2P1.isSelected();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ChkOpt1P1 = new javax.swing.JCheckBox();
        ChkOpt2P1 = new javax.swing.JCheckBox();
        ChkOpt3P1 = new javax.swing.JCheckBox();
        ChkOpt4P1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        Rbt1P2 = new javax.swing.JRadioButton();
        Rbt2P2 = new javax.swing.JRadioButton();
        Rbt3P2 = new javax.swing.JRadioButton();
        Rbt4P2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        LblResultPregunta4 = new javax.swing.JLabel();
        ChkOpt3P3 = new javax.swing.JCheckBox();
        ChkOpt4P3 = new javax.swing.JCheckBox();
        ChkOpt1P3 = new javax.swing.JCheckBox();
        ChkOpt2P3 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ChkOpt3P5 = new javax.swing.JCheckBox();
        ChkOpt1P5 = new javax.swing.JCheckBox();
        ChkOpt2P5 = new javax.swing.JCheckBox();
        ChkOpt4P5 = new javax.swing.JCheckBox();
        ChkOpt5P5 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("RESULTADOS");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Pregunta 1 - 20%");

        ChkOpt1P1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkOpt1P1.setText("for(int i=5;i>=1;i--){ System.out.println(i); } ");
        ChkOpt1P1.setEnabled(false);
        ChkOpt1P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkOpt1P1ActionPerformed(evt);
            }
        });

        ChkOpt2P1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkOpt2P1.setText("for(int i=1;i>=5;i++){ System.out.println(i); } ");
        ChkOpt2P1.setEnabled(false);

        ChkOpt3P1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkOpt3P1.setText("for(int i=5;i>0;i--){ System.out.println(i); } ");
        ChkOpt3P1.setEnabled(false);

        ChkOpt4P1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkOpt4P1.setText("for(int i=5;i>=5;i--){System.out.println(i); } ");
        ChkOpt4P1.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Pregunta 2 - 20%");

        Rbt1P2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Rbt1P2.setText("12");
        Rbt1P2.setEnabled(false);

        Rbt2P2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Rbt2P2.setText("10");
        Rbt2P2.setEnabled(false);

        Rbt3P2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Rbt3P2.setText("Un error en tiempo de ejecución");
        Rbt3P2.setEnabled(false);

        Rbt4P2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Rbt4P2.setText("Ninguna de las anteriores.");
        Rbt4P2.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Pregunta 5 - 15%");

        LblResultPregunta4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblResultPregunta4.setText("jLabel5");

        ChkOpt3P3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkOpt3P3.setText("C) Error al dividir por cero");
        ChkOpt3P3.setEnabled(false);
        ChkOpt3P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkOpt3P3ActionPerformed(evt);
            }
        });

        ChkOpt4P3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkOpt4P3.setText("D) Ninguno d ellos anteriores");
        ChkOpt4P3.setEnabled(false);
        ChkOpt4P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkOpt4P3ActionPerformed(evt);
            }
        });

        ChkOpt1P3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkOpt1P3.setText("A) División exitosa, el resultado es 0;");
        ChkOpt1P3.setEnabled(false);
        ChkOpt1P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkOpt1P3ActionPerformed(evt);
            }
        });

        ChkOpt2P3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkOpt2P3.setText("B) División exitosa, el resultado es 1;");
        ChkOpt2P3.setEnabled(false);
        ChkOpt2P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkOpt2P3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Pregunta 3 - 20%");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Pregunta 4 - 20%");

        ChkOpt3P5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkOpt3P5.setText("Instancia de Clase");
        ChkOpt3P5.setEnabled(false);

        ChkOpt1P5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkOpt1P5.setText("Un Lenguaje de programación");
        ChkOpt1P5.setEnabled(false);

        ChkOpt2P5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkOpt2P5.setText("Características de Java");
        ChkOpt2P5.setEnabled(false);

        ChkOpt4P5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkOpt4P5.setText("Wait");
        ChkOpt4P5.setEnabled(false);

        ChkOpt5P5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkOpt5P5.setText("Palabra Reservada");
        ChkOpt5P5.setEnabled(false);

        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChkOpt3P1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ChkOpt1P1))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ChkOpt4P1)
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel7))
                                    .addComponent(ChkOpt2P1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Rbt1P2)
                                .addGap(42, 42, 42)
                                .addComponent(Rbt2P2)
                                .addGap(48, 48, 48)
                                .addComponent(Rbt3P2)
                                .addGap(28, 28, 28)
                                .addComponent(Rbt4P2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChkOpt1P3)
                                    .addComponent(ChkOpt3P3))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChkOpt2P3)
                                    .addComponent(ChkOpt4P3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(LblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(ChkOpt4P5)
                        .addGap(52, 52, 52)
                        .addComponent(ChkOpt5P5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblResultPregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ChkOpt1P5)
                                .addGap(18, 18, 18)
                                .addComponent(ChkOpt2P5)
                                .addGap(36, 36, 36)
                                .addComponent(ChkOpt3P5)))))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(573, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ChkOpt2P1)
                            .addComponent(ChkOpt1P1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChkOpt4P1)
                            .addComponent(ChkOpt3P1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rbt1P2)
                    .addComponent(Rbt2P2)
                    .addComponent(Rbt3P2)
                    .addComponent(Rbt4P2))
                .addGap(29, 29, 29)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkOpt1P3)
                    .addComponent(ChkOpt2P3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChkOpt4P3)
                    .addComponent(ChkOpt3P3))
                .addGap(61, 61, 61)
                .addComponent(LblResultPregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkOpt1P5)
                    .addComponent(ChkOpt2P5)
                    .addComponent(ChkOpt3P5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkOpt4P5)
                    .addComponent(ChkOpt5P5))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(362, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(218, 218, 218)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChkOpt1P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkOpt1P1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChkOpt1P1ActionPerformed

    private void ChkOpt3P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkOpt3P3ActionPerformed
        if(ChkOpt3P3.isSelected()){
            ChkOpt1P3.setEnabled(false);
            ChkOpt2P3.setEnabled(false);
            ChkOpt4P3.setEnabled(false);
        }else{
            ChkOpt1P3.setEnabled(true);
            ChkOpt2P3.setEnabled(true);
            ChkOpt4P3.setEnabled(true);
        }
    }//GEN-LAST:event_ChkOpt3P3ActionPerformed

    private void ChkOpt4P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkOpt4P3ActionPerformed
        if(ChkOpt4P3.isSelected()){
            ChkOpt1P3.setEnabled(false);
            ChkOpt2P3.setEnabled(false);
            ChkOpt3P3.setEnabled(false);
        }else{
            ChkOpt1P3.setEnabled(true);
            ChkOpt2P3.setEnabled(true);
            ChkOpt3P3.setEnabled(true);
        }
    }//GEN-LAST:event_ChkOpt4P3ActionPerformed

    private void ChkOpt1P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkOpt1P3ActionPerformed
        if(ChkOpt1P3.isSelected()){
            ChkOpt2P3.setEnabled(false);
            ChkOpt3P3.setEnabled(false);
            ChkOpt4P3.setEnabled(false);
        }else{
            ChkOpt2P3.setEnabled(true);
            ChkOpt3P3.setEnabled(true);
            ChkOpt4P3.setEnabled(true);
        }

    }//GEN-LAST:event_ChkOpt1P3ActionPerformed

    private void ChkOpt2P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkOpt2P3ActionPerformed
        if(ChkOpt2P3.isSelected()){
            ChkOpt1P3.setEnabled(false);
            ChkOpt3P3.setEnabled(false);
            ChkOpt4P3.setEnabled(false);
        }else{
            ChkOpt1P3.setEnabled(true);
            ChkOpt3P3.setEnabled(true);
            ChkOpt4P3.setEnabled(true);
        }

    }//GEN-LAST:event_ChkOpt2P3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFpagFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFpagFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFpagFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFpagFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFpagFinal(nombreU,datoPagFinal).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChkOpt1P1;
    private javax.swing.JCheckBox ChkOpt1P3;
    private javax.swing.JCheckBox ChkOpt1P5;
    private javax.swing.JCheckBox ChkOpt2P1;
    private javax.swing.JCheckBox ChkOpt2P3;
    private javax.swing.JCheckBox ChkOpt2P5;
    private javax.swing.JCheckBox ChkOpt3P1;
    private javax.swing.JCheckBox ChkOpt3P3;
    private javax.swing.JCheckBox ChkOpt3P5;
    private javax.swing.JCheckBox ChkOpt4P1;
    private javax.swing.JCheckBox ChkOpt4P3;
    private javax.swing.JCheckBox ChkOpt4P5;
    private javax.swing.JCheckBox ChkOpt5P5;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblResultPregunta4;
    private javax.swing.JRadioButton Rbt1P2;
    private javax.swing.JRadioButton Rbt2P2;
    private javax.swing.JRadioButton Rbt3P2;
    private javax.swing.JRadioButton Rbt4P2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
