/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author reisa
 */
public class JFpag4 extends javax.swing.JFrame{
    Ventanas ventana = new Ventanas(this);
    static Datos datoPag4;
    int itemIndexBox1=0;
    static String nombreUsuario;
    String txtReservedBox1="";
    String cob1="-";
    String cob2="-";
    String cob3="-";
    String cob4="-";
    String cob5="-";
    JFpagFinal pagFinal;

   // DefaultComboBoxModel model = new DefaultComboBoxModel();
    //======OBTENER OBJETOS =========
    
    public JFpag4(String usuario, Datos dato) {
        initComponents();
        nombreUsuario = usuario;
        LblNombre.setText("Hola "+usuario);
        datoPag4 = dato;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblPag1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblOption5 = new java.awt.Label();
        LblRespuesta1 = new javax.swing.JLabel();
        LblRespuesta2 = new javax.swing.JLabel();
        LblOption1 = new java.awt.Label();
        LblOption2 = new java.awt.Label();
        LblRespuesta3 = new javax.swing.JLabel();
        LblOption3 = new java.awt.Label();
        LblRespuesta5 = new javax.swing.JLabel();
        LblOption4 = new java.awt.Label();
        LblRespuesta4 = new javax.swing.JLabel();
        JCbox1 = new javax.swing.JComboBox<>();
        JCbox2 = new javax.swing.JComboBox<>();
        JCbox3 = new javax.swing.JComboBox<>();
        JCbox4 = new javax.swing.JComboBox<>();
        JCbox5 = new javax.swing.JComboBox<>();
        BtnTerminar = new javax.swing.JButton();
        BtnAtras = new javax.swing.JButton();
        LblMensaje = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 537));

        LblPag1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblPag1.setText("Página 4");

        jLabel1.setBackground(new java.awt.Color(255, 255, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESTE EJERCICIO TIENE UN VALOR DEL 15%");

        jLabel2.setBackground(new java.awt.Color(255, 255, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("UNIR PALABRAS");

        LblOption5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LblOption5.setForeground(new java.awt.Color(0, 153, 153));
        LblOption5.setName(""); // NOI18N
        LblOption5.setText("5) Void");

        LblRespuesta1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblRespuesta1.setText("Un Lenguaje de programación");

        LblRespuesta2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblRespuesta2.setText("Características de Java");

        LblOption1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LblOption1.setForeground(new java.awt.Color(51, 51, 255));
        LblOption1.setName(""); // NOI18N
        LblOption1.setText("1)    Java es");

        LblOption2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LblOption2.setForeground(new java.awt.Color(153, 0, 153));
        LblOption2.setName(""); // NOI18N
        LblOption2.setText("2) Polimorfismo, Herencia");

        LblRespuesta3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblRespuesta3.setText("Instancia de Clase");

        LblOption3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LblOption3.setForeground(new java.awt.Color(204, 0, 0));
        LblOption3.setName(""); // NOI18N
        LblOption3.setText("3)   Objeto");

        LblRespuesta5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblRespuesta5.setText("Palabra Reservada");

        LblOption4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LblOption4.setForeground(new java.awt.Color(0, 153, 0));
        LblOption4.setName(""); // NOI18N
        LblOption4.setText("4) Pausa en ejecucion");

        LblRespuesta4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblRespuesta4.setText("Wait");

        JCbox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JCbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5" }));
        JCbox1.setMinimumSize(new java.awt.Dimension(37, 23));
        JCbox1.setPreferredSize(new java.awt.Dimension(37, 23));
        JCbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCbox1ActionPerformed(evt);
            }
        });

        JCbox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JCbox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5" }));
        JCbox2.setMinimumSize(new java.awt.Dimension(37, 23));
        JCbox2.setPreferredSize(new java.awt.Dimension(37, 23));
        JCbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCbox2ActionPerformed(evt);
            }
        });

        JCbox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JCbox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5" }));
        JCbox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCbox3ActionPerformed(evt);
            }
        });

        JCbox4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JCbox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5" }));
        JCbox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCbox4ActionPerformed(evt);
            }
        });

        JCbox5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JCbox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5" }));
        JCbox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCbox5ActionPerformed(evt);
            }
        });

        BtnTerminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnTerminar.setForeground(new java.awt.Color(0, 102, 51));
        BtnTerminar.setText("Terminar");
        BtnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTerminarActionPerformed(evt);
            }
        });

        BtnAtras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnAtras.setForeground(new java.awt.Color(153, 0, 0));
        BtnAtras.setText("<--");
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        LblMensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblMensaje.setForeground(new java.awt.Color(204, 0, 0));
        LblMensaje.setToolTipText("");

        LblNombre.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Pregunta 5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(BtnAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(LblPag1)
                        .addGap(96, 96, 96)
                        .addComponent(LblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LblOption3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LblOption4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LblOption5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblOption2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JCbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCbox3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCbox4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCbox5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblRespuesta4)
                                    .addComponent(LblRespuesta5)
                                    .addComponent(LblRespuesta2)
                                    .addComponent(LblRespuesta3))
                                .addGap(82, 82, 82))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblOption1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JCbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LblRespuesta1)
                                .addGap(29, 29, 29))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(LblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblPag1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblOption1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblRespuesta1)
                        .addComponent(JCbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblOption2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JCbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblRespuesta2)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JCbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblRespuesta3))
                            .addComponent(LblOption3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(LblOption4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JCbox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblRespuesta4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblOption5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JCbox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblRespuesta5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(LblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        LblOption5.getAccessibleContext().setAccessibleName("5) Palabra reservada");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCbox1ActionPerformed
        String item1 = JCbox1.getSelectedItem().toString();
        String item2 = JCbox2.getSelectedItem().toString();
        String item3 = JCbox3.getSelectedItem().toString();
        String item4 = JCbox4.getSelectedItem().toString();
        String item5 = JCbox5.getSelectedItem().toString();
        
        itemIndexBox1 = JCbox1.getSelectedIndex();
        establecerColor(1,item1);
        if("-".equals(item1))
        {
            if(!"".equals(cob1))
            {
                if(cob1 !=item2 && cob1 !=item3 && cob1 !=item4 && cob1 !=item5)
                {
                    addElementCombo(cob1,-1,2,3,4,5);
                    txtReservedBox1 ="";
                }
            }
        }else
        {
            if(!"".equals(txtReservedBox1)){
                if(cob1 !=item2 && cob1 !=item3 && cob1 !=item4 && cob1 !=item5)
                {
                    addElementCombo(cob4,-1,2,3,4,5);
                    removeElementCombo(item1,-1,2,3,4,5);
                    txtReservedBox1 =item1; 
                }else{
                    removeElementCombo(item1,-1,2,3,4,5);
                    txtReservedBox1 =item1;
                }
                 
             }else
            {
                txtReservedBox1 =item1;
                addElementCombo(cob1,-1,2,3,4,5);
                removeElementCombo(item1,-1,2,3,4,5);
            }
        }
        cob1 = JCbox1.getSelectedItem().toString();
        cob2 = JCbox2.getSelectedItem().toString();
        cob3 = JCbox3.getSelectedItem().toString();
        cob4 = JCbox4.getSelectedItem().toString();
        cob5 = JCbox5.getSelectedItem().toString();
    }//GEN-LAST:event_JCbox1ActionPerformed

    private void JCbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCbox2ActionPerformed
        String item1 = JCbox1.getSelectedItem().toString();
        String item2 = JCbox2.getSelectedItem().toString();
        String item3 = JCbox3.getSelectedItem().toString();
        String item4 = JCbox4.getSelectedItem().toString();
        String item5 = JCbox5.getSelectedItem().toString();
        
        itemIndexBox1 = JCbox2.getSelectedIndex();
        establecerColor(2,item2);
        if("-".equals(item2))
        {
            if(!"".equals(cob2))
            {
                if(cob2 !=item1 && cob2 !=item3 && cob2 !=item4 && cob2 !=item5)
                {
                    addElementCombo(cob2,1,-2,3,4,5);
                    txtReservedBox1 ="";
                }
            }
        }else
        {
            if(!"".equals(txtReservedBox1)){
                if(cob2 !=item1 && cob2 !=item3 && cob2 !=item4 && cob2 !=item5)
                {
                    addElementCombo(cob2,1,-2,3,4,5);
                    removeElementCombo(item2,1,-2,3,4,5);
                    txtReservedBox1 =item2; 
                }else{
                    addElementCombo(cob2,1,-2,3,4,5);
                    removeElementCombo(item2,1,-2,3,4,5);
                    txtReservedBox1 =item2;
                }
                 
             }else
            {
                txtReservedBox1 =item2;
                removeElementCombo(item2,1,-2,3,4,5);
            }
        }
        cob1 = JCbox1.getSelectedItem().toString();
        cob2 = JCbox2.getSelectedItem().toString();
        cob3 = JCbox3.getSelectedItem().toString();
        cob4 = JCbox4.getSelectedItem().toString();
        cob5 = JCbox5.getSelectedItem().toString();
    }//GEN-LAST:event_JCbox2ActionPerformed

    private void JCbox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCbox3ActionPerformed
        String item3 = JCbox3.getSelectedItem().toString();
        String item1 = JCbox1.getSelectedItem().toString();
        String item2 = JCbox2.getSelectedItem().toString();
        String item4 = JCbox4.getSelectedItem().toString();
        String item5 = JCbox5.getSelectedItem().toString();
        
        itemIndexBox1 = JCbox3.getSelectedIndex();
        establecerColor(3,item3);
        if("-".equals(item3))
        {
            if(!"".equals(cob3))
            {
                if(cob3 !=item1 && cob3 !=item2 && cob3 !=item4 && cob3 !=item5)
                {
                    addElementCombo(cob3,1,2,-3,4,5);
                    txtReservedBox1 ="";
                }
            }
        }else
        {
            if(!"".equals(txtReservedBox1)){
                if(cob3 !=item1 && cob3 !=item2 && cob3 !=item4 && cob3 !=item5)
                {
                    addElementCombo(cob3,1,2,-3,4,5);
                    removeElementCombo(item3,1,2,-3,4,5);
                    txtReservedBox1 =item3; 
                }else{
                    removeElementCombo(item3,1,2,-3,4,5);
                    txtReservedBox1 =item3;
                }
                 
             }else
            {
                txtReservedBox1 =item3;
                addElementCombo(cob3,1,2,-3,4,5);
                removeElementCombo(item3,1,2,-3,4,5);
            }
        }
        cob1 = JCbox1.getSelectedItem().toString();
        cob2 = JCbox2.getSelectedItem().toString();
        cob3 = JCbox3.getSelectedItem().toString();
        cob4 = JCbox4.getSelectedItem().toString();
        cob5 = JCbox5.getSelectedItem().toString();
    }//GEN-LAST:event_JCbox3ActionPerformed

    private void JCbox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCbox4ActionPerformed
        String item1 = JCbox1.getSelectedItem().toString();
        String item2 = JCbox2.getSelectedItem().toString();
        String item3 = JCbox3.getSelectedItem().toString();
        String item4 = JCbox4.getSelectedItem().toString();
        String item5 = JCbox5.getSelectedItem().toString();
        
        itemIndexBox1 = JCbox4.getSelectedIndex();
        establecerColor(4,item4);
        if("-".equals(item4))
        {
            if(!"".equals(cob4))
            {
                if(cob4 !=item1 && cob4 !=item2 && cob4 !=item3 && cob4 !=item5)
                {
                    addElementCombo(cob4,1,2,3,-4,5);
                    txtReservedBox1 ="";
                }
            }
        }else
        {
            if(!"".equals(txtReservedBox1)){
                if(cob4 !=item1 && cob4 !=item2 && cob4 !=item3 && cob4 !=item5)
                {
                    addElementCombo(cob4,1,2,3,-4,5);
                    removeElementCombo(item4,1,2,3,-4,5);
                    txtReservedBox1 =item4; 
                }else{
                    removeElementCombo(item4,1,2,3,-4,5);
                    txtReservedBox1 =item4;
                }
                 
             }else
            {
                txtReservedBox1 =item4;
                addElementCombo(cob4,1,2,3,-4,5);
                removeElementCombo(item4,1,2,3,-4,5);
            }
        }
        cob1 = JCbox1.getSelectedItem().toString();
        cob2 = JCbox2.getSelectedItem().toString();
        cob3 = JCbox3.getSelectedItem().toString();
        cob4 = JCbox4.getSelectedItem().toString();
        cob5 = JCbox5.getSelectedItem().toString();
    }//GEN-LAST:event_JCbox4ActionPerformed

    private void JCbox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCbox5ActionPerformed
        String item1 = JCbox1.getSelectedItem().toString();
        String item2 = JCbox2.getSelectedItem().toString();
        String item3 = JCbox3.getSelectedItem().toString();
        String item4 = JCbox4.getSelectedItem().toString();
        String item5 = JCbox5.getSelectedItem().toString();
        
        itemIndexBox1 = JCbox5.getSelectedIndex();
        establecerColor(5,item5);
        if("-".equals(item5))
        {
            if(!"".equals(cob5))
            {
                if(cob5 !=item1 && cob5 !=item2 && cob5 !=item3 && cob5 !=item4)
                {
                    addElementCombo(cob5,1,2,3,4,-5);
                    txtReservedBox1 ="";
                }
            }
        }else
        {
            if(!"".equals(txtReservedBox1)){
                if(cob5 !=item1 && cob5 !=item2 && cob5 !=item3 && cob5 !=item4)
                {
                    addElementCombo(cob5,1,2,3,4,-5);
                    removeElementCombo(item5,1,2,3,4,-5);
                    txtReservedBox1 =item5; 
                }else{
                    removeElementCombo(item5,1,2,3,4,-5);
                    txtReservedBox1 =item5;
                }
                 
             }else
            {
                txtReservedBox1 =item5;
                addElementCombo(cob5,1,2,3,4,-5);
                removeElementCombo(item5,1,2,3,4,-5);
            }
        }
        cob1 = JCbox1.getSelectedItem().toString();
        cob2 = JCbox2.getSelectedItem().toString();
        cob3 = JCbox3.getSelectedItem().toString();
        cob4 = JCbox4.getSelectedItem().toString();
        cob5 = JCbox5.getSelectedItem().toString();
    }//GEN-LAST:event_JCbox5ActionPerformed

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        ventana.ocutarVentana();
        JFpag3 pag3 = new JFpag3(nombreUsuario,datoPag4);
        
        
        ventana.abrirVentana(pag3);
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void BtnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTerminarActionPerformed
       
       
       String RtaJCbox1 =JCbox1.getSelectedItem().toString();
       String RtaJCbox2 =JCbox2.getSelectedItem().toString();
       String RtaJCbox3 =JCbox3.getSelectedItem().toString(); 
       String RtaJCbox4 =JCbox4.getSelectedItem().toString();
       String RtaJCbox5 =JCbox5.getSelectedItem().toString();
       
       if(RtaJCbox1.equals("-")|| RtaJCbox2.equals("-")|| RtaJCbox3.equals("-")|| RtaJCbox4.equals("-")|| RtaJCbox5.equals("-")){
           LblMensaje.setText("Debe ingresar todas las respuestas");
       }else 
       {           
           datoPag4.pregunta5_1 =RtaJCbox1 ;           
           datoPag4.pregunta5_2 =RtaJCbox2 ;
           datoPag4.pregunta5_3 =RtaJCbox3 ;
           datoPag4.pregunta5_4 =RtaJCbox4 ;
           datoPag4.pregunta5_5 =RtaJCbox5 ;

           
           pagFinal = new JFpagFinal(nombreUsuario,datoPag4);
           ventana.ocutarVentana();
           ventana.abrirVentana(pagFinal);
       }
    }//GEN-LAST:event_BtnTerminarActionPerformed

    public void addElementCombo(String item,int comboBox1,int comboBox2,int comboBox3,int comboBox4, int comboBox5){
        int size1 =JCbox1.getItemCount();
        int size2 =JCbox2.getItemCount();        
        int size3 =JCbox3.getItemCount();
        int size4 =JCbox4.getItemCount();
        int size5 =JCbox5.getItemCount();
        
        boolean encontrado =false;
        if(comboBox1==1)
        {
            for(int i =0; i < size1;i++)
            {
                String variable = JCbox1.getItemAt(i).toString();
                if( variable==item)
                {
                    encontrado =true;
                    break;
                }
            }
            if(!encontrado)
            {
                JCbox1.addItem(item);
            }
        }
        if(comboBox2==2)
        {
            for(int i =0; i < size2;i++)
            {
                String variable = JCbox2.getItemAt(i).toString();
                if( variable==item)
                {
                    encontrado =true;
                    break;
                }
            }
            if(!encontrado)
            {
                JCbox2.addItem(item);
            }
        }
        if(comboBox3==3)
        {
            for(int i =0; i < size3;i++)
            {
                String variable = JCbox3.getItemAt(i).toString();
                if( variable==item)
                {
                    encontrado =true;
                    break;
                }
            }
            if(!encontrado)
            {
                JCbox3.addItem(item);
            }
        }
        if(comboBox4==4)
        {
            for(int i =0; i < size4;i++)
            {
                String variable = JCbox4.getItemAt(i).toString();
                if( variable==item)
                {
                    encontrado =true;
                    break;
                }
            }
            if(!encontrado)
            {
                JCbox4.addItem(item);
            }
        }
        if(comboBox5==5)
        {
            for(int i =0; i < size5;i++)
            {
                String variable = JCbox5.getItemAt(i).toString();
                if( variable==item)
                {
                    encontrado =true;
                    break;
                }
            }
            if(!encontrado)
            {
                JCbox5.addItem(item);
            }
        }
    }
    
    public void removeElementCombo(String item,int comboBox1,int comboBox2,int comboBox3,int comboBox4 ,int comboBox5){
        int cicloBox  =0;
        int sizeB1 =JCbox1.getItemCount();
        int sizeB2 =JCbox2.getItemCount();        
        int sizeB3 =JCbox3.getItemCount();
        int sizeB4 =JCbox4.getItemCount();
        int sizeB5 =JCbox5.getItemCount();
        
        int itemEncontrado =-1;
        if(comboBox1==1)
        {
            //este ciclo busca el dato en el combo 2
            for(int i =0; i < sizeB1;i++)
            {
                String variable = JCbox1.getItemAt(i).toString();
                if( variable==item)
                {
                    itemEncontrado =i;
                    cicloBox=2;
                    break;
                }
            }
            if(cicloBox ==2)
            {
                if(itemEncontrado>0)
                {
                    JCbox1.removeItemAt(itemEncontrado);
                }
            }
        }
        if(comboBox2==2)
        {
            //este ciclo busca el dato en el combo 2
            for(int i =0; i < sizeB2;i++)
            {
                String variable = JCbox2.getItemAt(i).toString();
                if( variable==item)
                {
                    itemEncontrado =i;
                    cicloBox=2;
                    break;
                }
            }
            if(cicloBox ==2)
            {
                if(itemEncontrado>0)
                {
                    JCbox2.removeItemAt(itemEncontrado);
                }
            }
        }
        if(comboBox3==3)
        {
            for(int i =0; i < sizeB3;i++)
            {
                String variable = JCbox3.getItemAt(i).toString();
                if( variable==item)
                {
                    itemEncontrado =i;
                    cicloBox=3;
                    break;
                }
            }
            if(cicloBox ==3)
            {
                if(itemEncontrado>0)
                {
                    JCbox3.removeItemAt(itemEncontrado);
                }
            }
        }
        if(comboBox4==4)
        {
            for(int i =0; i < sizeB4;i++)
            {
                String variable = JCbox4.getItemAt(i).toString();
                if( variable==item)
                {
                    itemEncontrado =i;
                    cicloBox=4;
                    break;
                }
            }
            if(cicloBox ==4)
            {
                if(itemEncontrado>0)
                {
                    JCbox4.removeItemAt(itemEncontrado);
                }
            }
        }
         if(comboBox5==5)
        {
            for(int i =0; i < sizeB5;i++)
            {
                String variable = JCbox5.getItemAt(i).toString();
                if( variable==item)
                {
                    itemEncontrado =i;
                    cicloBox=5;
                    break;
                }
            }
            if(cicloBox ==5)
            {
                if(itemEncontrado>0)
                {
                    JCbox5.removeItemAt(itemEncontrado);
                }
            }
        }
    }
    
    public void establecerColor(int comboBox, String item){
        if(comboBox ==1)
        {
            if("".equals(item)||"-".equals(item))
            {
                LblRespuesta1.setForeground(Color.BLACK);
            }else
            {
                if(item=="1"){
                    LblRespuesta1.setForeground(LblOption1.getForeground());
                }
                if(item=="2"){
                    LblRespuesta1.setForeground(LblOption2.getForeground());
                }
                if(item=="3"){
                    LblRespuesta1.setForeground(LblOption3.getForeground());
                }
                if(item=="4"){
                    LblRespuesta1.setForeground(LblOption4.getForeground());
                }
                if(item=="5"){
                    LblRespuesta1.setForeground(LblOption5.getForeground());
                }
            }
        }
        if(comboBox ==2)
        {
            if("".equals(item)||"-".equals(item))
            {
                LblRespuesta2.setForeground(Color.BLACK);
            }else
            {
                if(item=="1")
                {
                    LblRespuesta2.setForeground(LblOption1.getForeground());
                }
                if(item=="2"){
                    LblRespuesta2.setForeground(LblOption2.getForeground());
                }
                if(item=="3"){
                    LblRespuesta2.setForeground(LblOption3.getForeground());
                }
                if(item=="4"){
                    LblRespuesta2.setForeground(LblOption4.getForeground());
                }
                if(item=="5"){
                    LblRespuesta2.setForeground(LblOption5.getForeground());
                }
            }
        }
        if(comboBox ==3)
        {
            if("".equals(item)||"-".equals(item))
            {
                LblRespuesta3.setForeground(Color.BLACK);
            }else
            {
                if(item=="1")
                {
                    LblRespuesta3.setForeground(LblOption1.getForeground());
                }
                if(item=="2"){
                    LblRespuesta3.setForeground(LblOption2.getForeground());
                }
                if(item=="3"){
                    LblRespuesta3.setForeground(LblOption3.getForeground());
                }
                if(item=="4"){
                    LblRespuesta3.setForeground(LblOption4.getForeground());
                }
                if(item=="5"){
                    LblRespuesta3.setForeground(LblOption5.getForeground());
                }
            }
        }
        if(comboBox ==4)
        {
            if("".equals(item)||"-".equals(item))
            {
                LblRespuesta4.setForeground(Color.BLACK);
            }else
            {
                if(item=="1")
                {
                    LblRespuesta4.setForeground(LblOption1.getForeground());
                }
                if(item=="2"){
                    LblRespuesta4.setForeground(LblOption2.getForeground());
                }
                if(item=="3"){
                    LblRespuesta4.setForeground(LblOption3.getForeground());
                }
                if(item=="4"){
                    LblRespuesta4.setForeground(LblOption4.getForeground());
                }
                if(item=="5"){
                    LblRespuesta4.setForeground(LblOption5.getForeground());
                }
            }
        }
        if(comboBox ==5)
        {
            if("".equals(item)||"-".equals(item))
            {
                LblRespuesta5.setForeground(Color.BLACK);
            }else
            {
                if(item=="1")
                {
                    LblRespuesta5.setForeground(LblOption1.getForeground());
                }
                if(item=="2"){
                    LblRespuesta5.setForeground(LblOption2.getForeground());
                }
                if(item=="3"){
                    LblRespuesta5.setForeground(LblOption3.getForeground());
                }
                if(item=="4"){
                    LblRespuesta5.setForeground(LblOption4.getForeground());
                }
                if(item=="5"){
                    LblRespuesta5.setForeground(LblOption5.getForeground());
                }
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFpag4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFpag4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFpag4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFpag4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFpag4(nombreUsuario,datoPag4).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnTerminar;
    private javax.swing.JComboBox<String> JCbox1;
    private javax.swing.JComboBox<String> JCbox2;
    private javax.swing.JComboBox<String> JCbox3;
    private javax.swing.JComboBox<String> JCbox4;
    private javax.swing.JComboBox<String> JCbox5;
    private javax.swing.JLabel LblMensaje;
    private javax.swing.JLabel LblNombre;
    private java.awt.Label LblOption1;
    private java.awt.Label LblOption2;
    private java.awt.Label LblOption3;
    private java.awt.Label LblOption4;
    private java.awt.Label LblOption5;
    private javax.swing.JLabel LblPag1;
    private javax.swing.JLabel LblRespuesta1;
    private javax.swing.JLabel LblRespuesta2;
    private javax.swing.JLabel LblRespuesta3;
    private javax.swing.JLabel LblRespuesta4;
    private javax.swing.JLabel LblRespuesta5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
